### ISSUE TITLE
cannot import name 'TreeStyle' from 'ete3'

### ISSUE THREAD

**Issue by 3719left** [ARise-fox/iPhylo-CLI#1]
ImportError: cannot import name 'TreeStyle' from 'ete3' (/home/val/anaconda3/envs/iphylo/lib/python3.8/site-packages/ete3/__init__.py)
Similar to https://github.com/etetoolkit/ete/issues/315

It is solved after "pip install pyqt5"

I guess pyqt needs to be added to requirement.txt

**Comment by ARise-fox** [comment]
Hi,

Thank you for reporting this issue.

I've updated the requirements.txt file to include pyqt5 to ensure all dependencies are installed correctly.

Please pull the latest changes or manually add pyqt5 to your requirements.txt to resolve this issue.

Thanks for bringing this to our attention!
